#####
#' Calculate Common Information Criteria
#'
#' @description Calculates three common information criteria of models estimated by \code{ols()}.
#'
#' @param mod linear model object generated by \code{ols()}.
#' @param which string value specifying the type of criterion: \code{"aic"} (Akaike Information Criterion), \code{"sic"} (Schwarz Information Criterion), or \code{"pc"}, (Prognostic Criterion), optional, if omitted then all criteria are returned (\code{"all"}).
#' @param scaled logical value which indicates whether criteria should be scaled by the number of observations T.
#'
#' @return A data frame of AIC, SIC, and PC values.
#'
#' @export
#'
#' @importFrom stats deviance
#'
#' @examples
#' wage.est <- ols(wage ~ educ + age, data = data.wage)
#' ols.infocrit(wage.est) # Return all criteria unscaled
#' ols.infocrit(wage.est, scaled = TRUE) # Return all criteria scaled
#' ols.infocrit(wage.est, which = "pc") # Return Prognostic Criterion unscaled
#'
#' @concept Akaike Information Criterion
#' @concept Schwarz Criterion
#' @concept Prognostic Criterion
#'
#####
ols.infocrit = function(mod, which = "all", scaled = FALSE){
  n = mod$nobs
  if (which == "aic"){
    val = log(deviance(mod)/n) + 2 * mod$ncoef/n
  }
  if (which == "sic"){
    val = log(deviance(mod)/n) + log(n) * mod$ncoef/n
  }
  if (which == "pc"){
    val = deviance(mod)/n * (n + mod$ncoef)/(n - mod$ncoef)
  }
  if (which == "all"){
    val = c(log(deviance(mod)/n) + 2 * mod$ncoef/n,
            log(deviance(mod)/n) + log(n) * mod$ncoef/n,
            deviance(mod)/n * (n + mod$ncoef)/(n - mod$ncoef))
    names(val) = c("AIC","SIC","PC")
  }
  if (scaled == T){val = n*val}
  return(val)
}
